
#eureka注册中心地址
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka

spring:
  #数据源
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.18.21:3306/zc-database-kaifa2?serverTimezone=UTC
    username: root
    password: Sci&1230
  #服务名
  application:
    name: client1
  jpa:
    show-sql: true




#端口号
server:
  port: 8080
mybatis:
  mapper-locations: "classpath*:mapper/*.xml"
  type-aliases-package: com.scistor.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  helperDialect: mysql
  reasonalbe: true
  supportMethodsArguments: true
  params: count=countSql


logging.level.com.dc.pcasweb.mapper: debug